### ISSUE TITLE
Use array directly to store Turing machine tape

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/boilerplate#223]
https://github.com/sCrypt-Inc/boilerplate/blob/e7131bd7991e33c72a54b7a0ea2270ffb3fc91d6/src/contracts/turingMachine.ts#L192

**Comment by xhliu** [comment]
Also we update https://xiaohuiliu.medium.com/turing-machine-on-bitcoin-7f0ebe0d52b1 afterwards.

**Comment by msinkec** [comment]
ArrayUtils are used to emulate the behavior of an array using a byte string. Correct me if I'm wrong, but I think byte strings were used exactly because of the limitations of arrays. We could make the size of the tape fixed by an upper bound but we still can't use a dynamic head index as indices need to be CTCs for arrays.
